"""empty message

Revision ID: 02c59af85f2c
Revises: 999bfceb8b2d
Create Date: 2022-03-20 16:49:21.619332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c59af85f2c'
down_revision = '999bfceb8b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('latitude', sa.Numeric(), nullable=True))
    op.add_column('hospital', sa.Column('longitude', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital', 'longitude')
    op.drop_column('hospital', 'latitude')
    # ### end Alembic commands ###
