"""empty message

Revision ID: 999bfceb8b2d
Revises: 
Create Date: 2022-03-20 10:32:02.761310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999bfceb8b2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=40), nullable=False),
    sa.Column('tel', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_table('member',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('pwd', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member')
    op.drop_table('hospital')
    # ### end Alembic commands ###
